name: Publish Draft Build
on: 
  pull_request:
    types: [labeled]
   
jobs:
  netlify:
    if: (github.actor == 'fastpages-chatops[bot]') && (contains(join(github.event.pull_request.*.labels), 'draft build pending'))
    runs-on: ubuntu-latest
    steps:
      - name: checkout the branch of the PR
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
    
