name: Publish Draft Build
on: 
  pull_request:
    types: [labeled]
   
jobs:
  netlify:
    if: (github.actor == 'fastpages-chatops[bot]') && (contains(join(github.event.pull_request.*.labels), 'draft build pending'))
    runs-on: ubuntu-latest
    steps:
      - name: checkout the branch of the PR
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
  
      - name: checkout master branch for action files
        uses: actions/checkout@v2
        with:
          path: master_reference

      - name: install netlify
        run: npm install netlify-cli -g

      - name: push draft build
        run: |
          netlify deploy --dir _site > python master_reference/_action_files/parse_netlify.py
          
