name: Publish Draft Build
on: 'push'
#   pull_request:
#     types: [labeled]
   
jobs:
  netlify:
    env:
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
#     if: (github.actor == 'fastpages-chatops[bot]') && (contains(join(github.event.pull_request.labels.*.name), 'draft build pending'))
    runs-on: ubuntu-latest
    steps:        
      - name: install netlify
        run: sudo npm install netlify-cli -g
          
      - name: verify netlify status
        run: netlify status
        env:
         NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
         NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
            
      - uses: actions/setup-python@v1
        with:
          python-version: '3.6'
          architecture: 'x64'

      - name: checkout the branch of the PR
        uses: actions/checkout@master
        with:
          ref: ${{ github.event.pull_request.head.sha }}
  
#       - name: checkout master branch for action files
#         uses: actions/checkout@v2
#         with:
#           path: _master_reference
        
#       - name: setup directories for Jekyll build
#         run: |
#           rm -rf _site
#           sudo chmod -R 777 .
          
#       - name: Jekyll build
#         uses: docker://jekyll/jekyll
#         with:
#           args: jekyll build --baseurl /

      - name: push draft build
        run: |
          sudo netlify deploy --dir _site | tee _action_files/netlify_logs.txt
          
      - name: get url
        id: url
        run: | 
          cd _action_files/
          cat netlify_logs.txt | python parse_netlify.py
          
      - name: make comment on PR 
        run: |
           cd _action_files/
           MSG="Preview of this branch has been generated at sha: $SHA and can be viewed at: ${URL}"
           echo $MSG
           ./pr_comment.sh $MSG
        env:
           URL: ${{ steps.py.url.draft_url }}
           SHA: ${{ github.event.pull_request.head.sha }}
         
          
