name: GH-Pages Status
on:
  page_build
  
jobs:
  see-page-build-payload:
    runs-on: ubuntu-latest
    steps:
      - run: echo $PAYLOAD
        env:
          PAYLOAD: ${{ toJSON(github.event.status) }}
