name: Notebook Build
on:
  push:
    branches:
      - master
    # paths:
    #   - '_notebooks/*.ipynb'

jobs:
  convert-notebook:
    if: contains(join(github.event.commits.*.message), '/sync')
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - uses: fastai/fastpages@master
      with:
        BOOL_SAVE_MARKDOWN: true
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        FORMAT: 'notebook'

    - name: setup directories for Jekyll build
      run: |
        rm -rf _site
        sudo chmod -R 777 .

    - name: Jekyll build
      uses: docker://jekyll/jekyll
      with:
        args: jekyll build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_site
