name: Notebook to Blog Post
on:
  push:
    branches:
      - master
    # paths:
    #   - '_notebooks/*.ipynb'

jobs:
  convert-notebook:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repository Contents
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - uses: fastai/fastpages@master
      with:
        BOOL_SAVE_MARKDOWN: true
        SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        FORMAT: 'notebook'

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./_site