name: python
on: push

jobs:
  py:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
          
      - name: add check run
        shell: python
        run: |
          import os

          headers = {'authorization': f'token {os.getenv('GITHUB_REPOSITORY')}',
           'accept': 'application/vnd.github.antiope-preview+json'}

          print(headers)
          
 